/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgraderRouteImport } from './routes/upgrader'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SeasonPassRouteImport } from './routes/season-pass'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as DikdokRouteImport } from './routes/dikdok'
import { Route as CosmeticsRouteImport } from './routes/cosmetics'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BaddiesRouteImport } from './routes/baddies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as CrewsIndexRouteImport } from './routes/crews.index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PlaySplitStealRouteImport } from './routes/play.split-steal'
import { Route as PlaySlotsRouteImport } from './routes/play.slots'
import { Route as PlayRouletteRouteImport } from './routes/play.roulette'
import { Route as PlayPokerRouteImport } from './routes/play.poker'
import { Route as PlayObbyRouteImport } from './routes/play.obby'
import { Route as PlayFlappyRouteImport } from './routes/play.flappy'
import { Route as PlayDiceDominionRouteImport } from './routes/play.dice-dominion'
import { Route as PlayDiceRouteImport } from './routes/play.dice'
import { Route as PlayCoinflipRouteImport } from './routes/play.coinflip'
import { Route as PlayBlackjackRouteImport } from './routes/play.blackjack'
import { Route as MarketplaceNewRouteImport } from './routes/marketplace.new'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as CrewsNewRouteImport } from './routes/crews.new'
import { Route as CrewsIdRouteImport } from './routes/crews.$id'
import { Route as ChallengesNewRouteImport } from './routes/challenges.new'
import { Route as ChallengesIdRouteImport } from './routes/challenges.$id'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ChallengesIdSubmitRouteImport } from './routes/challenges.$id.submit'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const UpgraderRoute = UpgraderRouteImport.update({
  id: '/upgrader',
  path: '/upgrader',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonPassRoute = SeasonPassRouteImport.update({
  id: '/season-pass',
  path: '/season-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const DikdokRoute = DikdokRouteImport.update({
  id: '/dikdok',
  path: '/dikdok',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmeticsRoute = CosmeticsRouteImport.update({
  id: '/cosmetics',
  path: '/cosmetics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BaddiesRoute = BaddiesRouteImport.update({
  id: '/baddies',
  path: '/baddies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewsIndexRoute = CrewsIndexRouteImport.update({
  id: '/crews/',
  path: '/crews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySplitStealRoute = PlaySplitStealRouteImport.update({
  id: '/play/split-steal',
  path: '/play/split-steal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySlotsRoute = PlaySlotsRouteImport.update({
  id: '/play/slots',
  path: '/play/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRouletteRoute = PlayRouletteRouteImport.update({
  id: '/play/roulette',
  path: '/play/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPokerRoute = PlayPokerRouteImport.update({
  id: '/play/poker',
  path: '/play/poker',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayObbyRoute = PlayObbyRouteImport.update({
  id: '/play/obby',
  path: '/play/obby',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayFlappyRoute = PlayFlappyRouteImport.update({
  id: '/play/flappy',
  path: '/play/flappy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDiceDominionRoute = PlayDiceDominionRouteImport.update({
  id: '/play/dice-dominion',
  path: '/play/dice-dominion',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDiceRoute = PlayDiceRouteImport.update({
  id: '/play/dice',
  path: '/play/dice',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCoinflipRoute = PlayCoinflipRouteImport.update({
  id: '/play/coinflip',
  path: '/play/coinflip',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayBlackjackRoute = PlayBlackjackRouteImport.update({
  id: '/play/blackjack',
  path: '/play/blackjack',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceNewRoute = MarketplaceNewRouteImport.update({
  id: '/marketplace/new',
  path: '/marketplace/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/marketplace/$id',
  path: '/marketplace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewsNewRoute = CrewsNewRouteImport.update({
  id: '/crews/new',
  path: '/crews/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewsIdRoute = CrewsIdRouteImport.update({
  id: '/crews/$id',
  path: '/crews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesNewRoute = ChallengesNewRouteImport.update({
  id: '/challenges/new',
  path: '/challenges/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIdRoute = ChallengesIdRouteImport.update({
  id: '/challenges/$id',
  path: '/challenges/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesIdSubmitRoute = ChallengesIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ChallengesIdRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/baddies': typeof BaddiesRoute
  '/chat': typeof ChatRoute
  '/cosmetics': typeof CosmeticsRoute
  '/dikdok': typeof DikdokRoute
  '/friends': typeof FriendsRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/missions': typeof MissionsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/season-pass': typeof SeasonPassRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/upgrader': typeof UpgraderRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/challenges/$id': typeof ChallengesIdRouteWithChildren
  '/challenges/new': typeof ChallengesNewRoute
  '/crews/$id': typeof CrewsIdRoute
  '/crews/new': typeof CrewsNewRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/play/blackjack': typeof PlayBlackjackRoute
  '/play/coinflip': typeof PlayCoinflipRoute
  '/play/dice': typeof PlayDiceRoute
  '/play/dice-dominion': typeof PlayDiceDominionRoute
  '/play/flappy': typeof PlayFlappyRoute
  '/play/obby': typeof PlayObbyRoute
  '/play/poker': typeof PlayPokerRoute
  '/play/roulette': typeof PlayRouletteRoute
  '/play/slots': typeof PlaySlotsRoute
  '/play/split-steal': typeof PlaySplitStealRoute
  '/u/$username': typeof UUsernameRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/crews/': typeof CrewsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/play/': typeof PlayIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/challenges/$id/submit': typeof ChallengesIdSubmitRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/baddies': typeof BaddiesRoute
  '/chat': typeof ChatRoute
  '/cosmetics': typeof CosmeticsRoute
  '/dikdok': typeof DikdokRoute
  '/friends': typeof FriendsRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/missions': typeof MissionsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/season-pass': typeof SeasonPassRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/upgrader': typeof UpgraderRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/challenges/$id': typeof ChallengesIdRouteWithChildren
  '/challenges/new': typeof ChallengesNewRoute
  '/crews/$id': typeof CrewsIdRoute
  '/crews/new': typeof CrewsNewRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/play/blackjack': typeof PlayBlackjackRoute
  '/play/coinflip': typeof PlayCoinflipRoute
  '/play/dice': typeof PlayDiceRoute
  '/play/dice-dominion': typeof PlayDiceDominionRoute
  '/play/flappy': typeof PlayFlappyRoute
  '/play/obby': typeof PlayObbyRoute
  '/play/poker': typeof PlayPokerRoute
  '/play/roulette': typeof PlayRouletteRoute
  '/play/slots': typeof PlaySlotsRoute
  '/play/split-steal': typeof PlaySplitStealRoute
  '/u/$username': typeof UUsernameRoute
  '/challenges': typeof ChallengesIndexRoute
  '/crews': typeof CrewsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/play': typeof PlayIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/challenges/$id/submit': typeof ChallengesIdSubmitRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/baddies': typeof BaddiesRoute
  '/chat': typeof ChatRoute
  '/cosmetics': typeof CosmeticsRoute
  '/dikdok': typeof DikdokRoute
  '/friends': typeof FriendsRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/missions': typeof MissionsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/season-pass': typeof SeasonPassRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/upgrader': typeof UpgraderRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/challenges/$id': typeof ChallengesIdRouteWithChildren
  '/challenges/new': typeof ChallengesNewRoute
  '/crews/$id': typeof CrewsIdRoute
  '/crews/new': typeof CrewsNewRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/play/blackjack': typeof PlayBlackjackRoute
  '/play/coinflip': typeof PlayCoinflipRoute
  '/play/dice': typeof PlayDiceRoute
  '/play/dice-dominion': typeof PlayDiceDominionRoute
  '/play/flappy': typeof PlayFlappyRoute
  '/play/obby': typeof PlayObbyRoute
  '/play/poker': typeof PlayPokerRoute
  '/play/roulette': typeof PlayRouletteRoute
  '/play/slots': typeof PlaySlotsRoute
  '/play/split-steal': typeof PlaySplitStealRoute
  '/u/$username': typeof UUsernameRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/crews/': typeof CrewsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/play/': typeof PlayIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/challenges/$id/submit': typeof ChallengesIdSubmitRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/baddies'
    | '/chat'
    | '/cosmetics'
    | '/dikdok'
    | '/friends'
    | '/gallery'
    | '/leaderboard'
    | '/mcp'
    | '/missions'
    | '/notifications'
    | '/profile'
    | '/season-pass'
    | '/settings'
    | '/trades'
    | '/upgrader'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/challenges/$id'
    | '/challenges/new'
    | '/crews/$id'
    | '/crews/new'
    | '/marketplace/$id'
    | '/marketplace/new'
    | '/play/blackjack'
    | '/play/coinflip'
    | '/play/dice'
    | '/play/dice-dominion'
    | '/play/flappy'
    | '/play/obby'
    | '/play/poker'
    | '/play/roulette'
    | '/play/slots'
    | '/play/split-steal'
    | '/u/$username'
    | '/challenges/'
    | '/crews/'
    | '/marketplace/'
    | '/play/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/challenges/$id/submit'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/baddies'
    | '/chat'
    | '/cosmetics'
    | '/dikdok'
    | '/friends'
    | '/gallery'
    | '/leaderboard'
    | '/mcp'
    | '/missions'
    | '/notifications'
    | '/profile'
    | '/season-pass'
    | '/settings'
    | '/trades'
    | '/upgrader'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/challenges/$id'
    | '/challenges/new'
    | '/crews/$id'
    | '/crews/new'
    | '/marketplace/$id'
    | '/marketplace/new'
    | '/play/blackjack'
    | '/play/coinflip'
    | '/play/dice'
    | '/play/dice-dominion'
    | '/play/flappy'
    | '/play/obby'
    | '/play/poker'
    | '/play/roulette'
    | '/play/slots'
    | '/play/split-steal'
    | '/u/$username'
    | '/challenges'
    | '/crews'
    | '/marketplace'
    | '/play'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/challenges/$id/submit'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/baddies'
    | '/chat'
    | '/cosmetics'
    | '/dikdok'
    | '/friends'
    | '/gallery'
    | '/leaderboard'
    | '/mcp'
    | '/missions'
    | '/notifications'
    | '/profile'
    | '/season-pass'
    | '/settings'
    | '/trades'
    | '/upgrader'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/challenges/$id'
    | '/challenges/new'
    | '/crews/$id'
    | '/crews/new'
    | '/marketplace/$id'
    | '/marketplace/new'
    | '/play/blackjack'
    | '/play/coinflip'
    | '/play/dice'
    | '/play/dice-dominion'
    | '/play/flappy'
    | '/play/obby'
    | '/play/poker'
    | '/play/roulette'
    | '/play/slots'
    | '/play/split-steal'
    | '/u/$username'
    | '/challenges/'
    | '/crews/'
    | '/marketplace/'
    | '/play/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/challenges/$id/submit'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BaddiesRoute: typeof BaddiesRoute
  ChatRoute: typeof ChatRoute
  CosmeticsRoute: typeof CosmeticsRoute
  DikdokRoute: typeof DikdokRoute
  FriendsRoute: typeof FriendsRoute
  GalleryRoute: typeof GalleryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  McpRoute: typeof McpRoute
  MissionsRoute: typeof MissionsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SeasonPassRoute: typeof SeasonPassRoute
  SettingsRoute: typeof SettingsRoute
  TradesRoute: typeof TradesRoute
  UpgraderRoute: typeof UpgraderRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ChallengesIdRoute: typeof ChallengesIdRouteWithChildren
  ChallengesNewRoute: typeof ChallengesNewRoute
  CrewsIdRoute: typeof CrewsIdRoute
  CrewsNewRoute: typeof CrewsNewRoute
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  MarketplaceNewRoute: typeof MarketplaceNewRoute
  PlayBlackjackRoute: typeof PlayBlackjackRoute
  PlayCoinflipRoute: typeof PlayCoinflipRoute
  PlayDiceRoute: typeof PlayDiceRoute
  PlayDiceDominionRoute: typeof PlayDiceDominionRoute
  PlayFlappyRoute: typeof PlayFlappyRoute
  PlayObbyRoute: typeof PlayObbyRoute
  PlayPokerRoute: typeof PlayPokerRoute
  PlayRouletteRoute: typeof PlayRouletteRoute
  PlaySlotsRoute: typeof PlaySlotsRoute
  PlaySplitStealRoute: typeof PlaySplitStealRoute
  UUsernameRoute: typeof UUsernameRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  CrewsIndexRoute: typeof CrewsIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrader': {
      id: '/upgrader'
      path: '/upgrader'
      fullPath: '/upgrader'
      preLoaderRoute: typeof UpgraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season-pass': {
      id: '/season-pass'
      path: '/season-pass'
      fullPath: '/season-pass'
      preLoaderRoute: typeof SeasonPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dikdok': {
      id: '/dikdok'
      path: '/dikdok'
      fullPath: '/dikdok'
      preLoaderRoute: typeof DikdokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmetics': {
      id: '/cosmetics'
      path: '/cosmetics'
      fullPath: '/cosmetics'
      preLoaderRoute: typeof CosmeticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baddies': {
      id: '/baddies'
      path: '/baddies'
      fullPath: '/baddies'
      preLoaderRoute: typeof BaddiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crews/': {
      id: '/crews/'
      path: '/crews'
      fullPath: '/crews/'
      preLoaderRoute: typeof CrewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/split-steal': {
      id: '/play/split-steal'
      path: '/play/split-steal'
      fullPath: '/play/split-steal'
      preLoaderRoute: typeof PlaySplitStealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/slots': {
      id: '/play/slots'
      path: '/play/slots'
      fullPath: '/play/slots'
      preLoaderRoute: typeof PlaySlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/roulette': {
      id: '/play/roulette'
      path: '/play/roulette'
      fullPath: '/play/roulette'
      preLoaderRoute: typeof PlayRouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/poker': {
      id: '/play/poker'
      path: '/play/poker'
      fullPath: '/play/poker'
      preLoaderRoute: typeof PlayPokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/obby': {
      id: '/play/obby'
      path: '/play/obby'
      fullPath: '/play/obby'
      preLoaderRoute: typeof PlayObbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/flappy': {
      id: '/play/flappy'
      path: '/play/flappy'
      fullPath: '/play/flappy'
      preLoaderRoute: typeof PlayFlappyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/dice-dominion': {
      id: '/play/dice-dominion'
      path: '/play/dice-dominion'
      fullPath: '/play/dice-dominion'
      preLoaderRoute: typeof PlayDiceDominionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/dice': {
      id: '/play/dice'
      path: '/play/dice'
      fullPath: '/play/dice'
      preLoaderRoute: typeof PlayDiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/coinflip': {
      id: '/play/coinflip'
      path: '/play/coinflip'
      fullPath: '/play/coinflip'
      preLoaderRoute: typeof PlayCoinflipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/blackjack': {
      id: '/play/blackjack'
      path: '/play/blackjack'
      fullPath: '/play/blackjack'
      preLoaderRoute: typeof PlayBlackjackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/new': {
      id: '/marketplace/new'
      path: '/marketplace/new'
      fullPath: '/marketplace/new'
      preLoaderRoute: typeof MarketplaceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crews/new': {
      id: '/crews/new'
      path: '/crews/new'
      fullPath: '/crews/new'
      preLoaderRoute: typeof CrewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crews/$id': {
      id: '/crews/$id'
      path: '/crews/$id'
      fullPath: '/crews/$id'
      preLoaderRoute: typeof CrewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/new': {
      id: '/challenges/new'
      path: '/challenges/new'
      fullPath: '/challenges/new'
      preLoaderRoute: typeof ChallengesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$id': {
      id: '/challenges/$id'
      path: '/challenges/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof ChallengesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$id/submit': {
      id: '/challenges/$id/submit'
      path: '/submit'
      fullPath: '/challenges/$id/submit'
      preLoaderRoute: typeof ChallengesIdSubmitRouteImport
      parentRoute: typeof ChallengesIdRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChallengesIdRouteChildren {
  ChallengesIdSubmitRoute: typeof ChallengesIdSubmitRoute
}

const ChallengesIdRouteChildren: ChallengesIdRouteChildren = {
  ChallengesIdSubmitRoute: ChallengesIdSubmitRoute,
}

const ChallengesIdRouteWithChildren = ChallengesIdRoute._addFileChildren(
  ChallengesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BaddiesRoute: BaddiesRoute,
  ChatRoute: ChatRoute,
  CosmeticsRoute: CosmeticsRoute,
  DikdokRoute: DikdokRoute,
  FriendsRoute: FriendsRoute,
  GalleryRoute: GalleryRoute,
  LeaderboardRoute: LeaderboardRoute,
  McpRoute: McpRoute,
  MissionsRoute: MissionsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SeasonPassRoute: SeasonPassRoute,
  SettingsRoute: SettingsRoute,
  TradesRoute: TradesRoute,
  UpgraderRoute: UpgraderRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ChallengesIdRoute: ChallengesIdRouteWithChildren,
  ChallengesNewRoute: ChallengesNewRoute,
  CrewsIdRoute: CrewsIdRoute,
  CrewsNewRoute: CrewsNewRoute,
  MarketplaceIdRoute: MarketplaceIdRoute,
  MarketplaceNewRoute: MarketplaceNewRoute,
  PlayBlackjackRoute: PlayBlackjackRoute,
  PlayCoinflipRoute: PlayCoinflipRoute,
  PlayDiceRoute: PlayDiceRoute,
  PlayDiceDominionRoute: PlayDiceDominionRoute,
  PlayFlappyRoute: PlayFlappyRoute,
  PlayObbyRoute: PlayObbyRoute,
  PlayPokerRoute: PlayPokerRoute,
  PlayRouletteRoute: PlayRouletteRoute,
  PlaySlotsRoute: PlaySlotsRoute,
  PlaySplitStealRoute: PlaySplitStealRoute,
  UUsernameRoute: UUsernameRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  CrewsIndexRoute: CrewsIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
