// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isPublishableApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_");
}

function readEnv(name: string) {
  const viteEnv = import.meta.env as Record<string, string | undefined>;
  const nodeEnv = typeof process !== "undefined" ? process.env : undefined;
  return viteEnv[name] || nodeEnv?.[name];
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) new Headers(init.headers).forEach((value, key) => headers.set(key, value));

    // Publishable keys are opaque API keys. Keep `apikey`, but do not send
    // an opaque key as a bearer JWT before a user session exists.
    if (isPublishableApiKey(supabaseKey) && headers.get("Authorization") === `Bearer ${supabaseKey}`) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Support both current publishable-key names and older anon-key deployments.
  const SUPABASE_URL = readEnv("VITE_SUPABASE_URL")
    || readEnv("VITE_PUBLIC_SUPABASE_URL")
    || readEnv("SUPABASE_URL");
  const SUPABASE_PUBLISHABLE_KEY = readEnv("VITE_SUPABASE_PUBLISHABLE_KEY")
    || readEnv("VITE_PUBLIC_SUPABASE_PUBLISHABLE_KEY")
    || readEnv("VITE_SUPABASE_ANON_KEY")
    || readEnv("SUPABASE_PUBLISHABLE_KEY")
    || readEnv("SUPABASE_ANON_KEY");

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["VITE_SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["VITE_SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: { fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY) },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: "pkce",
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
